version: "3.7"

networks:
  dockerapi-dev:
    driver: bridge

services:

  web-api:
    build:
      context: .
      dockerfile: Dockerfile
   depends_on:
     - "db"
    ports:
      - "3000:3000"
#    environment:
#      DB_CONNECTION_STRING: "host=db;port=5432;database=food-order-db;username=postgres;password=postgres"
    networks:
      - dockerapi-dev

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: food-order-db
    volumes:
      - postgres_data_volume:/var/lib/postgressql/data
      - ./db_scripts/EFMigrations.sql:/docker-entrypoint-initdb.d/EFMigrations.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data_volume:
    external: true